<?php
/**
 * Application configuration.
 * This file is generated by the deploy script. Do not commit with real credentials.
 */
return [
    'db' => [
        'host'     => 'localhost',
        'port'     => 3306,
        'database' => 'cardtable',
        'username' => 'cardtable_user',
        'password' => 'CHANGE_ME',
        'charset'  => 'utf8mb4',
    ],
    'pusher' => [
        'app_id'  => 'YOUR_APP_ID',
        'key'     => 'YOUR_KEY',
        'secret'  => 'YOUR_SECRET',
        'cluster' => 'YOUR_CLUSTER',
        'use_tls' => true,
    ],
    'mail' => [
        'smtp_host' => 'smtp.mailgun.org',
        'smtp_port' => 587,
        'smtp_user' => 'CHANGE_ME',
        'smtp_pass' => 'CHANGE_ME',
        'from_addr' => 'noreply@cardtable.example.com',
        'from_name' => 'Card Table',
    ],
    'app' => [
        'name'             => 'Card Table',
        'url'              => 'https://cardtable.example.com',
        'session_ttl'      => 86400,
        'otp_ttl'          => 600,
        'otp_max_attempts' => 5,
        'max_upload_size'  => 2097152,
    ],
];
